const express = require("express");
const router = express.Router();

// Mount all modules here
router.use("/", require("./auth.route.js"));
router.use("/", require("./user.route.js"));
router.use("/", require("./dashboard.route.js"));
router.use("/applications", require("./application.route.js"));
router.use("/my-applications", require("./my-application.route.js"));
router.use("/letter-templates", require("./letter-template.route.js"));
router.use("/letter-addressee-templates", require("./letter-addressee-template.route.js"));
router.use("/cheti", require("./certificate.route.js"));
router.use("/vyeti", require("./certificate-issuance.route.js"));
router.use("/", require("./v2-alias.route.js"));

// Legacy frontend modules now registered centrally through web.js
router.use("/", require("../controllers/maombi/anzishaShuleRequestController"));
router.use("/", require("../controllers/maombi/umilikinaumenejaRequestController"));
router.use("/", require("../controllers/maombi/kusajiliBinafsiRequestController"));
router.use("/", require("../controllers/maombi/kusajiliSerikaliRequestController"));
router.use("/", require("../controllers/maombi/kusajiliCommentController"));
router.use("/", require("../controllers/maombi/kuongezaMikondoRequestController"));
router.use("/", require("../controllers/maombi/kubadiliJinaRequestController"));
router.use("/", require("../controllers/maombi/kuongezaTahasusiRequestController"));
router.use("/", require("../controllers/maombi/kuongezaBweniRequestController"));
router.use("/", require("../controllers/maombi/ongezaDahaliaRequestController"));
router.use("/", require("../controllers/maombi/kubadiliUsajiliRequestController"));
router.use("/", require("../controllers/maombi/hamishaRequestController"));
router.use("/", require("../controllers/maombi/badiliMmilikiRequestController"));
router.use("/", require("../controllers/maombi/badiliMenejaRequestController"));
router.use("/", require("../controllers/maombi/futaShuleRequestController"));
router.use("/", require("../controllers/regionController"));
router.use("/", require("../controllers/districtController"));
router.use("/", require("../controllers/wardController"));
router.use("/", require("../controllers/streetController"));
router.use("/", require("../controllers/roleController"));
router.use("/", require("../controllers/permissionController"));
router.use("/", require("../controllers/moduleController"));
router.use("/", require("../controllers/rankController"));
router.use("/", require("../controllers/hierarchyController"));
router.use("/", require("../controllers/designationController"));
router.use("/", require("../controllers/zoneController"));
router.use("/", require("../controllers/attachmentTypeController"));
router.use("/", require("../controllers/applicationCategoryController"));
router.use("/", require("../controllers/schoolCategoryController"));
router.use("/", require("../controllers/schoolSubCategoryController"));
router.use("/", require("../controllers/schoolTypeStandardController"));
router.use("/", require("../controllers/schoolInfrastructureStandardController"));
router.use("/", require("../controllers/subjectController"));
router.use("/", require("../controllers/combinationSubjectController"));
router.use("/", require("../controllers/registrationTypeController"));
router.use("/", require("../controllers/applicantController"));
router.use("/", require("../controllers/schoolController"));
router.use("/", require("../controllers/schoolFilesController"));
router.use("/", require("../controllers/updateShoolDetailController"));
router.use("/", require("../controllers/combinationController"));
router.use("/", require("../controllers/biasController"));
router.use("/", require("../controllers/feeController"));
router.use("/", require("../controllers/algorithmController"));
router.use("/", require("../controllers/schoolFileNumberMappingController"));
router.use("/", require("../controllers/workflowController"));
router.use("/", require("../controllers/actionTypeController"));
router.use("/", require("../controllers/trackApplicationController"));
router.use("/", require("../controllers/attachmentController"));
router.use("/", require("../controllers/notificationController"));
router.use("/", require("../controllers/ripoti/RipotiRequestKuanzishaController"));
router.use("/", require("../controllers/ripoti/RipotiRequestUsajiliController"));
router.use("/", require("../controllers/ripoti/RipotiRequestWamilikiController"));
router.use("/", require("../controllers/ripoti/RipotiRequestMenejaController"));
router.use("/", require("../controllers/ripoti/RipotiRequestMabadilikoController"));
router.use("/", require("../controllers/barua/maombiBaruaController"));
router.use("/", require("../controllers/barua/baruaController"));
router.use("/", require("../controllers/loginActivityController"));
router.use("/", require("../controllers/auditTrailController"));
router.use("/", require("../controllers/systemLogController"));
router.use("/", require("../controllers/aiSupportController"));
router.use("/", require("../controllers/systemConfigurationController"));
router.use("/", require("../controllers/handoverController"));
router.use("/", require("../controllers/religionController"));
router.use("/", require("../controllers/languageController"));
router.use("/", require("../controllers/handleSessionController"));
router.use("/", require("../controllers/errorController"));

module.exports = router;
